In [1]:
import pandas as pd

df = pd.read_csv("heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [2]:
import numpy as np
from scipy.stats import zscore
import matplotlib.pyplot as plt

In [3]:
print(df.columns)

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [4]:
df = df[df['Cholesterol'] != 0]
df = df[df['RestingBP'] != 0]

In [5]:
# Remove outliers:

cols = ['MaxHR', 'Cholesterol', 'RestingBP', 'Oldpeak']
df['Z'] = df[cols].apply(zscore).abs().max(axis = 1)

df_clean = df[df['Z'] < 3]

In [6]:
df_dummies = pd.get_dummies(df, 
                            columns = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'],
                            drop_first = True)

In [7]:
print(df_dummies.columns)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Z', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP',
       'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST',
       'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='object')

In [8]:
df_dummies.keys()

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Z', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP',
       'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST',
       'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up'],
      dtype='object')

In [9]:
df_dummies

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Z,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1.296470,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,1.561980,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,1.722993,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,1.314958,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,0.982980,True,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1.333019,True,False,False,True,True,False,False,True,False
914,68,144,193,1,141,3.4,1,2.330281,True,False,False,False,True,False,False,True,False
915,57,130,131,0,115,1.2,1,1.922314,True,False,False,False,True,False,True,True,False
916,57,130,236,0,174,0.0,1,1.378077,False,True,False,False,False,False,False,True,False
917,38,138,175,0,173,0.0,0,1.337274,True,False,True,False,True,False,False,False,True

In [10]:
df_dummies.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Z
count,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000
mean,52.882038,133.022788,244.635389,0.167560,140.226542,0.901609,0.477212,1.433860
std,9.505888,17.282750,59.153524,0.373726,24.524107,1.072861,0.499816,0.684842
min,28.000000,92.000000,85.000000,0.000000,69.000000,-0.100000,0.000000,0.281314
25%,46.000000,120.000000,207.250000,0.000000,122.000000,0.000000,0.000000,0.982980
50%,54.000000,130.000000,237.000000,0.000000,140.000000,0.500000,0.000000,1.331700
75%,59.000000,140.000000,275.000000,0.000000,160.000000,1.500000,1.000000,1.722993
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000,6.062277

In [12]:
X = df_dummies.drop('HeartDisease', axis = 1)
y = df_dummies['HeartDisease']

In [13]:
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 746, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.35607325,  0.40398044,  0.7504942 , ..., -0.79074163,
        -0.95029534,  1.06655324],
       [-0.40865641,  1.5619801 , -1.09340492, ..., -0.79074163,
         1.05230444, -0.9375997 ],
       [-1.67187886, -0.17501939,  0.64899516, ..., -0.79074163,
        -0.95029534,  1.06655324],
       ...,
       [ 0.43349189, -0.17501939, -1.92231369, ...,  1.26463557,
         1.05230444, -0.9375997 ],
       [ 0.43349189, -0.17501939, -0.1460806 , ..., -0.79074163,
         1.05230444, -0.9375997 ],
       [-1.56661032,  0.28818048, -1.17798745, ..., -0.79074163,
        -0.95029534,  1.06655324]])

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.38, random_state = 94)

In [17]:
from sklearn.svm import SVC
model = SVC(kernel = 'linear')

In [18]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [19]:
model.score(X_test, y_test)

0.8063380281690141

In [20]:
model.fit(X_scaled, y)

SVC(kernel='linear')

In [21]:
model.score(X_scaled, y)

0.868632707774799

In [25]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    estimator = SVC(),
    n_estimators = 140,
    max_samples = 0.95,
    oob_score = True,
    random_state = 0
)

bag_model.fit(X_train, y_train)
bag_model.oob_score_

0.8896103896103896

In [26]:
bag_model.score(X_test, y_test)

0.8169014084507042

In [27]:
# Decision tree:

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

scores = cross_val_score(DecisionTreeClassifier(), X, y, cv = 9)
scores

array([0.81927711, 0.78313253, 0.85542169, 0.87951807, 0.84337349,
       0.73493976, 0.71084337, 0.69879518, 0.69512195])

In [28]:
scores.mean()

0.7800470173376433

In [34]:
bag_model = BaggingClassifier(
    estimator = DecisionTreeClassifier(),
    n_estimators = 160,
    max_samples = 0.84,
    oob_score = True,
    random_state = 0
)

scores = cross_val_score(bag_model, X, y, cv = 9)
scores.mean()

0.8456590590002286

In [33]:
scores

array([0.89156627, 0.90361446, 0.93975904, 0.92771084, 0.90361446,
       0.8313253 , 0.77108434, 0.73493976, 0.70731707])

<p style = 'font-size: 14px;">

### It is useful to use bagging during SVC and Decision Tree models because this will increase the predicted score. 

### Bagging helps reduce variance within a noisy dataset i.e: high variance and low bias models eg: KNNs, fully grown decision trees.

</p>

### It is useful to use bagging in both SVC and Decision tree classifiers as it will help increases prediction models.

### Bagging is best used in high variance and low bias models such as KNNs and fully grown decision trees.